kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sql-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: azurefile-storageclass
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi